grpc security jwt with rsa public key demo
yidongnan/grpc-spring-boot-starter pull request #409
Opened 2020-08-18 09:52 UTC by suveng

# grpc security jwt with rsa public key demo

## 服务间的调用逻辑

`cloud-grpc-sleuth-zipkin-user`用`grpc`调用`cloud-grpc-sleuth-zipkin-pay`
`cloud-grpc-sleuth-zipkin-user`用`grpc`调用`cloud-grpc-sleuth-zipkin-order`
`cloud-grpc-api`是存放`grpc`的`proto`文件
查看`cloud-grpc-sleuth-zipkin-user`中的`controller`, 里面简单写了一些测试逻辑

## 整合了sleuth和zipkin做链路追踪

查看`cloud-grpc-sleuth-zipkin-user`的`application.yml`配置文件
其他模块类似, 查看配置即可, 这里没有使用服务发现组件, 写死了`ip`

## 整合了`oauth2`的`jwt`令牌

使用`RSA`的公钥解密`JWT`
重载了解析`token`的逻辑, 获取到更细的权限, 详细查看`cloud-grpc-security-sleuth-zipkin-pay`的`SercurityConfig.java`和`GrpcJwtConverter.java`
`cloud-grpc-security-sleuth-zipkin-pay`支持多种方式的认证授权, `basicAuth`和`JWT`
其他模块,我没有配置,但是可以参考 cloud-grpc-security-sleuth-zipkin-pay 的配置
其中测试的过程, 我是写在了 `cloud-grpc-security-sleuth-zipkin-user 的 controller` 的逻辑中, 具体可查看 `PayController`
建议打断点,观察, 这只是`demo`, 注意`@secured`注解, 还有`oauth-server`的用户的权限必须是`ROLE_`开头, 1. 在授权就定义好格式 2. 可以在`converter`里面拼接, 两种实现, 这里我使用第一种方式
注意: `token`的获取需要自行从`oauth server`中获取

测试步骤:
1. 启动`oauth-server`, 获取一个`token`, 查看`oauth-server`的配置
2. 在`cloud-grpc-sleuth-zipkin-user`中替换`token`
3. 启动所有服务, 测试`cloud-grpc-sleuth-zipkin-user`的`controller`的逻辑

![LyOQbX](https://gitee.com/suveng/upic/raw/master/uPic/LyOQbX.png)

2020-08-18 09:59 UTC, ST-DDT commented
Please don't close and open new pull requests all the time. You can update the existing ones by pushing to the associated branch.

2020-08-18 10:02 UTC, suveng commented
> Please don't close and open new pull requests all the time. You can update the existing ones by pushing to the associated branch.

sorry, but i check pr document and run gradle task to passed the ci check; i didn't change the code expect change maven to gradle project.

2020-08-18 10:05 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-api/src/main/java/my/suveng/istio/grpc/api/order/Order.java
> +public final class Order {
These files are generated so they should be removed from the SCM and be re-generated during the build.

2020-08-18 10:07 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/README.md
> +![LyOQbX](https://gitee.com/suveng/upic/raw/master/uPic/LyOQbX.png)
If you are confident in your English skills please add an English variant as well.
If not, we will add them ourselves later.

2020-08-18 10:10 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-dependency/pom.xml
> +                <version>2.9.0.RELEASE</version>
Please update these to the lasted version `2.10.0.RELEASE`

2020-08-18 10:12 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-order/src/main/java/my/suveng/istiocloudorderdemo/config/SercurityConfig.java
> +public class SercurityConfig extends ResourceServerConfigurerAdapter {
Typo: `SecurityConfig `

2020-08-18 10:13 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-order/src/main/java/my/suveng/istiocloudorderdemo/consumer/GrpcConsumerSecurityConfig.java
> +	//}
Is this code related to your example?

2020-08-18 10:15 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-pay/src/main/java/my/suveng/istiocloudpaydemo/config/SercurityConfig.java
> +public class SercurityConfig extends ResourceServerConfigurerAdapter {
Typo: `SecurityConfig `

2020-08-18 10:17 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-user/src/main/java/my/suveng/istioclouduserdemo/config/SercurityConfig.java
> +public class SercurityConfig extends ResourceServerConfigurerAdapter {
Typo: `SecurityConfig`

2020-08-18 10:17 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-user/src/main/java/my/suveng/istioclouduserdemo/config/SercurityConfig.java
> +	 * @author suwenguang
No need to add the `@author` to every bean definition. Once on the class level is enough.

2020-08-19 09:22 UTC, suveng commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-api/src/main/java/my/suveng/istio/grpc/api/order/Order.java
> +public final class Order {
if these files doesn't exists it may case some problem

2020-08-19 09:28 UTC, suveng commented on examples/cloud-grpc-security-sleuth-zipkin/README.md
> +![LyOQbX](https://gitee.com/suveng/upic/raw/master/uPic/LyOQbX.png)
got it , todo!
my english skill is poor, but i would try

2020-08-19 09:28 UTC, suveng commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-order/src/main/java/my/suveng/istiocloudorderdemo/consumer/GrpcConsumerSecurityConfig.java
> +	//}
got it , i  will leave more annotation

2020-08-19 09:29 UTC, suveng commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-user/src/main/java/my/suveng/istioclouduserdemo/config/SercurityConfig.java
> +	 * @author suwenguang
got it

2020-08-19 20:36 UTC, ST-DDT requested changes

2020-08-19 20:36 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/build.gradle
> +    version = '1.0.0'
Please use a group name as specified in our main build.gradle:
https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/build.gradle#L244

2020-08-19 20:36 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-dependency/pom.xml
> +        </license>
Please choose MIT license, as the entire project uses that license

2020-08-19 20:36 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-dependency/pom.xml
> +                <version>1.0.6</version>
What does this library contain?

2020-08-19 20:36 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-order/pom.xml
> +        </dependency>
Wrong library

2020-08-19 20:36 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-order/build.gradle
> +    compile 'org.lognet:grpc-spring-boot-starter:2.4.3'
Wrong library

2020-08-19 20:36 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-pay/build.gradle
> +    compile 'org.lognet:grpc-spring-boot-starter:2.4.3'
Wrong library

2020-08-19 20:36 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-pay/pom.xml
> +        </dependency>
Wrong library

2020-08-19 20:36 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-user/build.gradle
> +    compile 'org.lognet:grpc-spring-boot-starter:2.4.3'
Wrong library

2020-08-19 20:36 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-user/pom.xml
> +        </dependency>
Wrong library

2020-08-19 20:36 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-pay/src/main/resources/application.yml
> +    base-url: http://192.168.9.208:9411
This should probably be localhost

2020-08-19 20:36 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/AuthenticatingServerInterceptor.java
> +    Context.Key<Authentication> AUTHENTICATION_CONTEXT_KEY = Context.key("authentication");
Please don't change files outside the scope of your PR as it makes it more difficult to review your PR.
(You could propose them in a different PR though)

2020-08-19 20:47 UTC, ST-DDT commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-api/src/main/java/my/suveng/istio/grpc/api/order/Order.java
> +public final class Order {
> other modules are based on this api module , so if these file are removed, the whole example project will report warning

I always keep them in a volatile location and I never had those issues, see `example/grpc-lib` for example.

> i have config the generated place in the source dir, if re-generate, these file will be overwrite

The build should not have any impact on the managed source code itself.

> so in order to make people watch the demo code directly, i prefer to keep them in project

These classes are hard to read and their content is fully covered by the proto file itself or are even self explanatory from the calls alone.

IMO they take away the focus from the files that actually matter such as the config classes.
Please remove them and let them generate in a place that won't get added to them SCM by mistake.

2020-08-20 06:49 UTC, suveng commented on examples/cloud-grpc-security-sleuth-zipkin/cloud-grpc-security-sleuth-zipkin-dependency/pom.xml
> +                <version>1.0.6</version>
it's my own util jar, nerver mind , i have deleted it

2020-08-20 06:50 UTC, suveng commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/security/interceptors/AuthenticatingServerInterceptor.java
> +    Context.Key<Authentication> AUTHENTICATION_CONTEXT_KEY = Context.key("authentication");
i don't remember i change the source code , maybe the spotless plugin did this.

2020-08-20 09:25 UTC, ST-DDT commented
Also the complexity/size of this demo is very large in comparison to the main project, if possible simplify it a bit.
FFR: Main project java files 113

2020-08-20 09:42 UTC, ST-DDT commented
I'm be busy the next days, so please ping me once you consider this PR ready for review.

2021-04-25 21:46 UTC, ST-DDT commented
Closing because there are too many classes that are not directly related to the example and add unnecessary complexity, that removes the attention to the actual required setup.

2021-04-25 21:46 UTC, closed without merging