增加zookeeper注册中心，统一各注册中心写法
yidongnan/grpc-spring-boot-starter pull request #475
Opened 2021-01-06 14:52 UTC by ZMRWEGO

2021-01-07 01:15 UTC, ZMRWEGO commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataEurekaConfiguration.java
> +        if (!Objects.isNull(eurekaRegistration)) {
Actually, it's a coding habit, using functions instead of expressions. It doesn't make any difference.

2021-01-08 13:53 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataEurekaConfiguration.java
> +        if (!Objects.isNull(eurekaRegistration)) {
AFAICT this project uses direct comparison and IMO this isn't easier to read than the other syntax, so for consistency please change it to `!= null` for now.

2021-01-08 14:24 UTC, ZMRWEGO commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataEurekaConfiguration.java
> +        if (!Objects.isNull(eurekaRegistration)) {
ok，it's right for consistency

2021-01-08 22:31 UTC, ST-DDT requested changes

2021-01-08 22:31 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetaDataZookeeperConfiguration.java
> +            final String port = String.valueOf(grpcServerProperties.getPort());
Please use `Integer#toString(int)` for the conversion, as this avoids autoboxing the `int`.

2021-01-08 22:31 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetaDataZookeeperConfiguration.java
> +            zookeeperRegistration.setPort(0);
Why do you set the port to `0` here? The other implementations don't change that port either.
AFAICT this defaults to/contains the web server port.

2021-01-08 22:31 UTC, ST-DDT commented on grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/GrpcUtils.java
> +    public static final String INTER_PROCESS_DISABLE = "-1";
IMO this should either be of type `int` or there should be two constant one with the value and one with the `_TEXT`. Please also add a short javadoc that explains what this value represents.
Something like:

````java
/**
 * The constant for the server port, that represents "don't start an inter process server (e.g. netty)".
 */
````

2021-01-08 22:31 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetaDataZookeeperConfiguration.java
> +    ZookeeperRegistration zookeeperRegistration;
This should be private similar to the other fields.

2021-01-08 22:31 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataConsulConfiguration.java
> +    }
Have you tested this implementation?
I'm not familiar with the discovery implementations so I'm a little bit scared when touching these.

Does gradle support profiles and are you familiar with them?
If yes, could you extend the cloud example with profiles for each of the currently supported discovery implementations or at least for zk/etcd? Then we could automate these tests via `testExamples.sh`.
If not, I will try to add it myself. I might need your help with a scripted setup of zk/etcd though.

2021-01-08 22:31 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataEurekaConfiguration.java
> +                eurekaRegistration.getInstanceConfig().getMetadataMap().put(GrpcUtils.CLOUD_DISCOVERY_METADATA_PORT,
Please move the `.put` to a new line to improve the readability (Similar to GrpcMetaDataZookeeperConfiguration).

2021-01-08 22:31 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetaDataZookeeperConfiguration.java
> +public class GrpcMetaDataZookeeperConfiguration {
```suggestion
public class GrpcMetadataZookeeperConfiguration {
```
To match the other class names.

2021-01-09 03:33 UTC, ZMRWEGO commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetaDataZookeeperConfiguration.java
> +            final String port = String.valueOf(grpcServerProperties.getPort());
- [ ]  done

2021-01-09 11:32 UTC, ZMRWEGO commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetaDataZookeeperConfiguration.java
> +            zookeeperRegistration.setPort(0);
不同的注册中心存放元数据的方式是不一样的，zookeeper 设置port为0，代表port下一步需要读取配置文件并更新。如果不设置的话会抛出NPE

2021-01-09 11:32 UTC, ZMRWEGO commented on grpc-common-spring-boot/src/main/java/net/devh/boot/grpc/common/util/GrpcUtils.java
> +    public static final String INTER_PROCESS_DISABLE = "-1";
fix

2021-01-09 11:32 UTC, ZMRWEGO commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetaDataZookeeperConfiguration.java
> +    ZookeeperRegistration zookeeperRegistration;
fix

2021-01-09 11:33 UTC, ZMRWEGO commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataConsulConfiguration.java
> +    }
我加了zookeeper和consul的使用例子，你可以看一下。数据成功注册到注册中心，并被成功消费

2021-01-09 11:34 UTC, ZMRWEGO commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataEurekaConfiguration.java
> +                eurekaRegistration.getInstanceConfig().getMetadataMap().put(GrpcUtils.CLOUD_DISCOVERY_METADATA_PORT,
fix

2021-01-09 11:34 UTC, ZMRWEGO commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetaDataZookeeperConfiguration.java
> +public class GrpcMetaDataZookeeperConfiguration {
什么意思，兄弟

2021-01-09 11:36 UTC, ZMRWEGO commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetaDataZookeeperConfiguration.java
> +public class GrpcMetaDataZookeeperConfiguration {
知道了，名字不规范，已经fix

2021-01-09 11:41 UTC, ZMRWEGO commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetaDataZookeeperConfiguration.java
> +            final String port = String.valueOf(grpcServerProperties.getPort());
但是貌似不会有自动装箱，可以看一下源码`public static String valueOf(int i) {
        return Integer.toString(i);
    }`

2021-01-09 11:49 UTC, ZMRWEGO commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetadataConsulConfiguration.java
> +    }
使用docker可以很方便的启动一个注册中心服务

2021-01-09 12:06 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcMetaDataZookeeperConfiguration.java
> +            final String port = String.valueOf(grpcServerProperties.getPort());
Yeah, you are right. I knew it did unnecessary work, I just didn't remember exactly what it was.

2021-01-09 12:07 UTC, ST-DDT commented
FFR: [English translation](https://translate.google.com/translate?hl=&sl=zh-CN&tl=en&u=https%3A%2F%2Fgithub.com%2Fyidongnan%2Fgrpc-spring-boot-starter%2Fpull%2F475)

2021-01-17 10:16 UTC, ST-DDT approved these changes
Looks good to me.

2021-01-17 10:22 UTC, merged

2021-01-17 10:24 UTC, ZMRWEGO commented
yeah,在单个k8s集群是可行的，但是在多个k8s集群就不行了