Feature/v2.10.1.release reuseport
yidongnan/grpc-spring-boot-starter pull request #484
Opened 2021-01-21 08:30 UTC by fogan

Two feature were added in this PR
1.Port reuse,when using ShadedNettyGrpcServerFactory,anather process can start its server in the same port. 
2.Graceful termination,when receive the signal of kill -15，the service does not stop immediately, but first completes the current task and then exits.

2021-01-21 08:52 UTC, ST-DDT requested changes
I'm not familiar with these options, the netty javadocs were empty and all I could find was "helps with faster restarts". How does it work/What does it do?

Please update your PR to the latest changes to resolve the merge conflicts.

2021-01-21 08:52 UTC, ST-DDT commented on build.gradle
> +        projectVersion = '2.10.1.1.RELEASE'
Please don't change the version number arbitarily in the PR. If you need a fast release, mention this in the description and we try to do that.

2021-01-21 08:52 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/ShadedNettyGrpcServerFactory.java
> +            return nettyServerBuilder;
Please also implement it for the non-shaded grpc server factory.

2021-02-08 07:09 UTC, fogan commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/ShadedNettyGrpcServerFactory.java
> +            return nettyServerBuilder;
> Please also implement it for the non-shaded grpc server factory.

This feature in shaded  is supported，but non-shaded is  not supported，which is given by grpc-community。
can u help me pr，and give me a fast verison or  snapshot，i am waitting to use this feature in my project。

2021-02-08 10:53 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/ShadedNettyGrpcServerFactory.java
> +            return nettyServerBuilder;
> > Please also implement it for the non-shaded grpc server factory.
> 
> This feature in shaded is supported，but non-shaded is not supported，which is given by grpc-community。

AFAIK grpc-netty and grpc-shaded-netty ues the exact same code, just with different packages.
I'll probably try it out myself.
Can you give me a little hint what this SO_REUSEPORT/SO_REUSEADDR does? Why does it need both?

> can u help me pr，and give me a fast verison or snapshot，i am waitting to use this feature in my project。

I could merge this faster, if you respond to my requests...
The v2.11.0 release will be ready/deployed soon, with or without this feature.
You can always build the jars locally. `gradlew publishToMavenLocal`

2021-04-25 21:50 UTC, ST-DDT commented
Closing because the questions related to this feature proposal haven't been answered at all.

2021-04-25 21:50 UTC, closed without merging