exception handling - best match
yidongnan/grpc-spring-boot-starter pull request #485
Opened 2021-01-21 17:55 UTC by anjeyy

In Addition to #465 , a more precise solution to resolving exception. Now Supports a convenient way of handling inherited Exceptions.

---

Example:

The following Structure of Exceptions is given and a **FirstLevelException** is thrown inside your application code
```java
public class ExceptionContainer {
    public static class MyRootRuntimeException extends RuntimeException {
        public MyRootRuntimeException(String msg) {
            super(msg);
        }
    }

    public static class FirstLevelException extends MyRootRuntimeException {
        public FirstLevelException(String msg) {
            super(msg);
        }
    }
}
```

Now with the following Advice you will get a precise Exception Handling where a thrown FirstLevelException is correctly executed for the precise depth of mapping. Without this PR, the execution **can** be for mapped _MyRootRuntimeException_.
```java
@GrpcAdvice
public class GrpcExceptionAdvice {

    @GrpcExceptionHandler
    public Status handleInvalidArgument(MyRootRuntimeException e) {
        return Status.INVALID_ARGUMENT.withDescription("Your description").withCause(e);
    }

    @GrpcExceptionHandler(FirstLevelException.class)
    public StatusException handleResourceNotFoundException(FirstLevelException e) {
        Status status = Status.NOT_FOUND.withDescription("Your description").withCause(e);
        return status.asException();
    }

}
```

---

TODO
- [x] implementation ✔️ 
- [x] unit tests ✔️ 
- [ ] review 🏁 in progress

2021-01-21 19:15 UTC, ST-DDT requested changes
One little change otherwise it looks good to me.

2021-01-21 19:15 UTC, ST-DDT commented on tests/src/test/java/net/devh/boot/grpc/test/advice/AdviceExceptionHandlingTest.java
>      void testThrownMyRootRuntimeException_IsNotMappedAndResultsInInvocationException() {
This test name should be adjusted as well.

2021-01-21 19:24 UTC, anjeyy commented on tests/src/test/java/net/devh/boot/grpc/test/advice/AdviceExceptionHandlingTest.java
>      void testThrownMyRootRuntimeException_IsNotMappedAndResultsInInvocationException() {
You're right. Done.

2021-01-21 21:09 UTC, ST-DDT approved these changes

2021-01-21 21:10 UTC, ST-DDT commented
Thanks for the improvement.

2021-01-22 22:03 UTC, merged

2021-01-30 02:31 UTC, ZMRWEGO commented on tests/src/test/java/net/devh/boot/grpc/test/advice/AdviceExceptionHandlingTest.java
>      void testThrownMyRootRuntimeException_IsNotMappedAndResultsInInvocationException() {
yes is‘s right

2021-01-30 02:33 UTC, ZMRWEGO commented on tests/src/test/java/net/devh/boot/grpc/test/advice/AdviceExceptionHandlingTest.java
>      void testThrownMyRootRuntimeException_IsNotMappedAndResultsInInvocationException() {
test