Ability to expose gRPC health through actuator
yidongnan/grpc-spring-boot-starter pull request #488
Opened 2021-01-25 17:42 UTC by eleduardo

Implements #433 

This PR implements a reactive healthcheck (made it reactive since exposing actuator via webflux is common) that exposes the status of the gRPC server.

The healthcheck is perfromed hitting the actual service since that actually proves that the server is indeed responding. It also follows a strict (yet configurable) deadline and forces a non-retry.

I did not send the event to the liveness/readiness since the whole health endpoint goes to 503 if a component is marked as out of traffic so /actuator/health can be used directly but nothing prevents the bean from also sending the event to the readiness/liveness probe.

No specific tests added in this PR or docs but pending comments I can make changes.

2021-01-29 16:52 UTC, eleduardo commented
Hi @ST-DDT or @yidongnan is there any chance to get feedback on this PR?

2021-01-30 11:09 UTC, ST-DDT commented
Yes, sorry for the delay. I try to wrap up the next release (v2.11.0) and currently don't have time to add a new feature to it. That being said, this won't be in the next release.

As for the actual content. You implementation uses reactive code, which isn't bad in itself, but it forces the users to add it to their code as well as seen in the tests. So maybe (also) adding a non-reactive variant might be a good alternative.
There is also https://github.com/yidongnan/grpc-spring-boot-starter/issues/411, which tries to run without the health service dependency. So I considered removing it from the default stack entirely/making it optional (especially if it does not serve any health states by default). A bridge might still be useful though.

2021-01-30 11:19 UTC, ST-DDT requested changes

2021-01-30 11:19 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/health/GrpcServerActuatorHealthIndicator.java
> +        }
IMO this should fail, if the deadline is invalid.

2021-01-30 11:19 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/health/GrpcServerActuatorHealthIndicator.java
> +        healthCheckClient = HealthGrpc.newFutureStub(channel);
There should be a constructor that passes this stub directly.

2021-01-30 11:19 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/health/GrpcServerActuatorHealthIndicator.java
> +    private HealthGrpc.HealthFutureStub healthCheckClient;
IMO a reactive class should use a reactive stub as well.
(I'm not sure whether there is a reactive implementation for this stub though)

2021-01-30 11:19 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/health/GrpcServerActuatorHealthIndicator.java
> +                .onErrorReturn(builder.withDetail(STATUS, DOWN_STATUS).status(Status.DOWN).build());
I'm not sure whether the `withDetail(STATUS, *)` serves any additional information in addition to `status(DOWN)` here.

2021-01-30 11:19 UTC, ST-DDT commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/health/GrpcServerActuatorHealthIndicator.java
> +                .check(HealthCheckRequest.newBuilder().build());
What about the other `services`?

2021-02-01 16:52 UTC, eleduardo commented on grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/health/GrpcServerActuatorHealthIndicator.java
> +    private HealthGrpc.HealthFutureStub healthCheckClient;
@ST-DDT I need to take a look at how spring does it but wondering if it is really worth having both... I'll double check and if the actuator running on a reactive model protects itself from the blocking implementation I'll just implement it with blocking code

2021-04-25 21:48 UTC, ST-DDT commented
Closing because requested changes haven't been made/addressed.

2021-04-25 21:48 UTC, closed without merging