Java 16 + gradle 7.0 compatibility
yidongnan/grpc-spring-boot-starter pull request #520
Opened 2021-04-16 08:27 UTC by popfalushi

Hello. Tried to build examples on gradle 6.8.3 and java 16 and build process failed for 3 reasons:
0. Gradle 6.8.3 failed with Could not compile initialization script 'C:\Users\popfa\AppData\Local\Temp\ijmapper.gradle'. Updated gradle to 7.0.
1. Lombok plugin needed update to be compatible with java 16. Changed plugin to io.freefair.lombok because it is recommended by Gradle.
2. Spotless plugin needed additional arguments in gradle.properties. For more information look here: https://github.com/diffplug/spotless/issues/834 . Plugin version got updated as well just because at first I thought that it will resolve the problem, but afterwards found issue on github. Didn't reverse plugin update after that.

After all changes local examples build and run ok, overall project also, javadoc is generated with getters/setters methods (checked on GrpcCodecDefinition class javadoc).

2021-04-16 08:35 UTC, popfalushi commented
As far as I understand, java 11 will pass the CI test and java 8 will be eternally failed because java 8 does not support --add-opens. Don't really know what to do with it. If java8 is essential than I suppose PR can be closed. Maybe in the future spotless plugin will do its job without need for add-opens, but at the same time lombok most likely will require it.

2021-04-16 08:40 UTC, ST-DDT commented
>     1. Changed plugin to io.freefair.lombok because it is recommended by Gradle.

Do you have a link for that? Or at least a comparison between these two?

2021-04-16 08:44 UTC, ST-DDT commented
> As far as I understand, java 11 will pass the CI test and java 8 will be eternally failed because java 8 does not support --add-opens. Don't really know what to do with it. If java8 is essential than I suppose PR can be closed. Maybe in the future spotless plugin will do its job without need for add-opens, but at the same time lombok most likely will require it.

Thats a though one. I'll have a look this weekend.

2021-04-16 08:52 UTC, popfalushi commented
> > ```
> > 1. Changed plugin to io.freefair.lombok because it is recommended by Gradle.
> > ```
> 
> Do you have a link for that? Or at least a comparison between these two?

My mistake - it is lombok project that recommends this plugin - gradle itself does not recommend anything. This plugin is referenced on official lombok page: https://projectlombok.org/setup/gradle and it is also under active development - it has milestone and stable version from April, the former plugin didn't get an update from last May.

FYI: Lombok right now is in the tough spot: https://github.com/rzwitserloot/lombok/issues/2681 . There were many discussions about it on reddit and hackernews.

2021-04-17 10:22 UTC, ST-DDT commented
IMO making our project compilable in the latest version is a good thing.
However, we should ensure that we generate Java 8 compatible jars (ClassVersion + Java Api), as there might still be developers out there that use that version for compatibility reasons.
Could you adjust the gradle file to always generate J8 compatible classes?

@yidongnan What do you think?

2021-04-17 18:35 UTC, ST-DDT commented
I included the gradle update in another PR that only updates dependencies #521, so that we can focus or changes here entirely to the J16 changes.

2021-05-02 19:08 UTC, ST-DDT requested changes
Could you please update your PR for the latest changes?

2021-05-03 13:41 UTC, popfalushi commented
in a week or two - right now I'm on holiday. But what about compatibility with java 8? My PR was incompatible with java 8 and it will stay this way in the future. If compatibity with java 8 is a must than what's the point?

If you are ready to ditch java 8 - I'll rebase this branch on current state, no problem.

2021-05-03 18:33 UTC, ST-DDT commented
> If you are ready to ditch java 8 - I'll rebase this branch on current state, no problem.

I'm not sure about that yet. Enjoy your holidays, after that there is still plenty of time to decide on this.

2021-11-22 22:36 UTC, ST-DDT commented
Fixes #604

2021-11-22 22:37 UTC, ST-DDT approved these changes
Sorry for the long wait. Lets get this merged.

2021-11-23 02:31 UTC, yidongnan commented on gradle.properties
> -  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
I think it's possible to add these jvm parameters depending on the Java version? I'll try it later

2021-11-23 05:14 UTC, yidongnan commented on gradle.properties
> -  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
@ST-DDT What do you think if the Java version is greater than 15 and we disable the spotless plugin?

2021-11-23 09:41 UTC, ST-DDT commented on gradle.properties
> -  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
I'd rather omit the java 17 compile time support for now and start compiling the project with JDK 11 (ClasssVersion still on Java 8) after the next release. Using the `javac --release 8` flag ensures that the produced releases are Java 8 compatible.
Then we can add the above settings to the gradle.properties and really support J17.

(I would like to release 2.13 this month, if both of our time permits.)

2021-11-24 10:28 UTC, yidongnan commented on gradle.properties
> -  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
@ST-DDT ok

2021-11-24 10:28 UTC, merged