Add GrpcClient soft bean registration and autowiring
yidongnan/grpc-spring-boot-starter pull request #580
Opened 2021-09-05 21:36 UTC by a-simeshin

### Context
There is a rather inconvenient problem described in https://github.com/yidongnan/grpc-spring-boot-starter/issues/463
@GrpcClient is not a @Bean, so we are encouraged to wrap it in a standard bean creation for quality of life.

### 
- [ ] register client as bean after injection section into BeanPostProcessor
- [ ] invoke autowire manually via AutowireCapableBeanFactory
- [ ] make sure the bean is created in context, @Autowired and @Qualifier are available for method and field injection
- [ ] proof it with unit test

2021-09-06 15:03 UTC, ST-DDT commented
I really like the idea of your change, but IMO the `@GrpcClient` bean in its current state supports multiple specific variations for a single client (name). Creating a bean for every `@GrpcClient` annotation would break existing code (duplicate bean definition) or behave randomly (e.g. due to the ranom bean initialization order).
How about adding a new annotation for that.

````java
/**
 * Annotation that can be added to `@Configuration` classes to create GrpcClient beans in the ApplicationContext.
 */
@Target(CLASS)
@Repeatable
public @interface GrpcClientBean {

    /** The type of the bean to create. */
    Class<?> clazz();

    /** The name of the bean to create. If empty, a name will be generated automatically based on the bean class and the client name. */
    String beanName() default "";

    /** The client definition used to create the bean. */
    GrpcClient definition();

}
````

Usage:

````java
@GrpcClientBean(clazz = SimpleServiceStub.class, definition = @GrpcClient("foobar"))
public class GrpcBeanConfig {

    MyAnotherExternalBean myExternalBean(SimpleServiceStub foobarSimpleServiceStub) {
        return new MyAnotherExternalBean (foobarSimpleServiceStub);
    }

}
````

I'm not sure whether we should add a `scope` option as the stubs themselves are immutable?

2021-09-06 15:13 UTC, ST-DDT commented
See also https://github.com/yidongnan/grpc-spring-boot-starter/issues/463
( I plan to refactor the bean post processor bean a bit to use an `GrpcStubInjector` to split the stub generation from the stub injection, this would hardly have any impact on the implementation of this feature )

2021-09-06 15:47 UTC, a-simeshin commented
> I really like the idea of your change, but IMO the `@GrpcClient` bean in its current state supports multiple specific variations for a single client (name). 

I thought about this problem. It seems to me that a good solution would be to declare the bean name as ``@GrpcClient value`` + ``class name`` of the stub, because it is impossible by means of this library to create two identical types of stubs for one client name.

Unfortunately, this idea has failed. 
I still don't understand why, when registering a bean name as ``name + injectionType.getSimpleName()``, then it cannot be found in the context by ``@Qualifier``, but when registering a bean name as ``Introspector.decapitalize(injectionType.getSimpleName())``, everything goes well. 
@ST-DDT, сould you be so kind to tell me why this is happening? It just blows my mind :(

> Creating a bean for every `@GrpcClient` annotation would break existing code (duplicate bean definition) or behave randomly (e.g. due to the ranom bean initialization order).

That is why "soft" registration of the bean is proposed with try catch and only warn. Without this, indeed, even in the examples of unit tests, it was clear that about 50% would break without proper softness. It seems to me that this solution should not break anything in existing projects, and tests confirm this, while allowing you to use all the advantages of ``@Bean`` in new projects.

> How about adding a new annotation for that.

To be honest, I don't like this solution, because for me all the beauty of this project is in 1 simple annotation that will do everything for you, then we will have more and more. On the other hand, we will be sure that nothing will break.
Anyway, @ST-DDT, I will trust your opinion and wait for your comment below. Will do it as you say

2021-09-06 18:34 UTC, ST-DDT commented
> > I really like the idea of your change, but IMO the `@GrpcClient` bean in its current state supports multiple specific variations for a single client (name).
> 
> I thought about this problem. It seems to me that a good solution would be to declare the bean name as `@GrpcClient value` + `class name` of the stub, because it is impossible by means of this library to create two identical types of stubs for one client name.
> 
> Unfortunately, this idea has failed.
> I still don't understand why, when registering a bean name as `name + injectionType.getSimpleName()`, then it cannot be found in the context by `@Qualifier`, but when registering a bean name as `Introspector.decapitalize(injectionType.getSimpleName())`, everything goes well.
> @ST-DDT, сould you be so kind to tell me why this is happening? It just blows my mind :(

After some debugging I managed to get it to work. In my case I either forgot to update one of the two `@Qualifier` annotations or had typos in them (other character case etc).

I modified the code a bit to make it easier to debug:

````java

         final String beanName = annotation.value()+ injectionType.getSimpleName();
//        final String beanName = Introspector.decapitalize(injectionType.getSimpleName());
        try {
            final ConfigurableListableBeanFactory beanFactory =
                    ((ConfigurableApplicationContext) this.applicationContext).getBeanFactory();
            final Set<String> names = Sets.newHashSet(beanFactory.getBeanNamesIterator());
            beanFactory.registerSingleton(beanName, value);
            final Set<String> names2 = Sets.newHashSet(beanFactory.getBeanNamesIterator());
            names2.removeAll(names);
            log.warn("New Names: {}", names2);

            this.applicationContext.getAutowireCapableBeanFactory().autowireBean(value);
        } catch (final Exception e) {
            log.warn("Could not register and autowire bean: {}", beanName, e);
        }
````

IMO distinguishing them by client name is a requirement, especially since the following is potentially frequently used (especially if spread over multiple classes/libraries):

````java
        @GrpcClient("test")
        TestServiceGrpc.TestServiceBlockingStub blockingStub;
        
        @GrpcClient("fallback")
        TestServiceGrpc.TestServiceBlockingStub fallbackBlockingStub;
````

> > Creating a bean for every `@GrpcClient` annotation would break existing code (duplicate bean definition) or behave randomly (e.g. due to the ranom bean initialization order).
> 
> That is why "soft" registration of the bean is proposed with try catch and only warn. Without this, indeed, even in the examples of unit tests, it was clear that about 50% would break without proper softness. It seems to me that this solution should not break anything in existing projects, and tests confirm this, while allowing you to use all the advantages of `@Bean` in new projects.

You are right. Your soft registration does not break any existing code, but it writes plenty of warning to the logs.
(That is if you have used `@GrpcClient SomeStub` in more than one class.)
If I just run the tests, I get 265 of these warnings. Sure the test code does not reflect real code, but this huge number still indicates, that there is an issue there (84 with client disambiguation).

> > How about adding a new annotation for that.
> 
> To be honest, I don't like this solution, because for me all the beauty of this project is in 1 simple annotation that will do everything for you, then we will have more and more. On the other hand, we will be sure that nothing will break.

Thanks for sharing your opinion. I summarized the benefits of each variant below, please comment, if I forgot something.

**Pro OneForAll:**

````java
@GrpcClient("client")
private MyStub myStub;
````

* Single annotation for all purposes
* Easy to define

**Pro ExtraAnnotation:**

````java
@GrpcClientBean(clazz = MyStub.class, definition = @GrpcClient("client"))
````

* Unambiguous
* Allows declaring multiple beans of a single type
* Allows customization of bean names
* No need to define a field just to create a bean
* Easy to define

From this summary, I still prefer the ExtraAnnotation variant, but that's just my opinion.
@yidongnan , @Shinigami92 what do you think would be the best way here? (feel free to propose other solutions as well)

2021-09-08 08:07 UTC, ST-DDT requested changes
I consulted with @Shinigami92 and we came to the conclusion, that the unambiguity of the bean definition is more important than having only a single annotation for all.

Please change your PR to create an extra annotation for grpc clients/stubs that will be added to the application context.

2021-09-09 08:12 UTC, a-simeshin commented
> I consulted with @Shinigami92 and we came to the conclusion, that the unambiguity of the bean definition is more important than having only a single annotation for all.
> 
> Please change your PR to create an extra annotation for grpc clients/stubs that will be added to the application context.

Thank you very much for the research after reanalysis, the solution with additional annotation looks better for me now. I`ll start ASAP on this week

Before starting, I propose to have your agreement with solution, that we should add annotation, which add to the context a bean
```java
/**
 * Annotation that can be added to `@Configuration` classes to create GrpcClient beans in the ApplicationContext.
 */
@Target(CLASS)
@Repeatable
public @interface GrpcClientBean {

    /** The type of the bean to create. */
    Class<?> clazz();

    /** The name of the bean to create. If empty, a name will be generated automatically based on the bean class and the client name. */
    String beanName() default "";

    /** The client definition used to create the bean. */
    GrpcClient definition();

}
```

But there are several questions that are not entirely clear to me:
1.  If the bean name is not specified, then should I create a bean with name ``GrpcClient.value()`` + ``clazz.getSimpleName()`` ?
2.  Should I call manually ``autowireBean(beanValue)`` after bin creation?
3.  Do I need to create a separate BeanPostProcessor class that will work only with this annotation, separately from ``@GrpcClient`` ?
4. Should I check, that class with annotation ``@GrpcBeanClient`` also annotated with ``@Configuration``? Or we can offer a softer solution?
4.  How a situation should be handled when an annotated field with ``@GrpcClient`` already declared manually in the class with annotation ``@GrpcBeanClient`` ?

2021-09-09 22:34 UTC, ST-DDT commented
> 2. Should I call manually `autowireBean(beanValue)` after bin creation?

I'm not sure about that. Will the beans get autowired if not called?
IMO it is not that important for now, as the `@grpcClient` injections aren't autowired till now.

> 3. Do I need to create a separate BeanPostProcessor class that will work only with this annotation, separately from `@GrpcClient` ?

No, IMO the existing post processor is good as it. It will get trimmed a bit when the injector will be split into a separate class.

> 4. Should I check, that class with annotation `@GrpcBeanClient` also annotated with `@Configuration`? Or we can offer a softer solution?

That's a good question. My first thought was we should check for the `@GrpcBeanClient` annotation, and if it isn't an annotated with `@Configuration`, then we should throw an exception. While it is probably not necessary to add the restriction, I hope to establish some good coding practices with that.

> 5. How a situation should be handled when an annotated field with `@GrpcClient` already declared manually in the class with annotation `@GrpcBeanClient` ?

IMO we should not add any additional limitations on these, so it will be possible to to have both `@GrpcClientBean` on the class itself and `@GrpcClient` on its fields.

Any suggestions regarding field names? I'm really not sure which names would be best.

- `clazz` or `type` or `beanType`
- `beanName` or `name`
- `definition` or `client`

2021-09-09 23:16 UTC, a-simeshin commented
> Any suggestions regarding field names? I'm really not sure which names would be best.
> 
> * `clazz` or `type` or `beanType`
> * `beanName` or `name`
> * `definition` or `client`

I think that simple and concise names just awesome. So ``clazz`` and ``client`` would be nice, but ``beanName`` allows to avoid misunderstandings with the name in the annotation ``@GrpcClient``, because it`s very likely that someone has already created a bean with the client's name in real projects (even me).

2021-09-10 19:59 UTC, a-simeshin commented
@ST-DDT would you be so kind to code review again? ``GrpcClientBeanInjectionTest`` with example of usage, also you were definitely right, living without beans hassle and warns in the log is much more better.

2021-09-12 11:55 UTC, ST-DDT requested changes
Looks good to me, I have just some small suggestions regarding the code readability.

2021-09-12 11:55 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +                        "Unsupported type " + injectionType.getName());
Have you checked, whether the exception message contains a reference to the annotated `@Configuration`?

2021-09-12 15:16 UTC, a-simeshin commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +                        : beanClientIterator.beanName();
Done

2021-09-12 15:21 UTC, a-simeshin commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +                            ((ConfigurableApplicationContext) this.applicationContext).getBeanFactory();
Done

2021-09-12 15:38 UTC, a-simeshin commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +                    log.warn("Could not register and autowire bean: {}", beanNameToCreate, e);
Done, but unfortunately I have no idea how to catch exceptions through ``AssertThrows`` at the stage of forming the context

2021-09-12 15:53 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +                    log.warn("Could not register and autowire bean: {}", beanNameToCreate, e);
No problem.

These work like plain JUnit tests without spring (no spring boot test annotations on the test class).
We start spring with the required configuration just inside the test.

It will look similar to this:

````java
@Test
void testFail() {
    SpringApplication app = new SpringApplication(TestConfig.class);
    assertThrows(SomeException.class, () -> app.run());
}
````

Do you wish to give it a try?

2021-09-12 16:16 UTC, a-simeshin commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +                        "Unsupported type " + injectionType.getName());
I added check for annotations ``@Configuration`` or ``@TestConfiguration``.
In addition added the name of the class where the error has occurred to the exception text.

2021-09-12 16:22 UTC, ST-DDT requested changes

2021-09-12 16:22 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/build.gradle
> +    api 'org.springframework.boot:spring-boot-starter-test'
We should not depend on this test dependency at runtime.

2021-09-12 16:22 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +        final TestConfiguration[] testConfigurationAnnotation = clazz.getAnnotationsByType(TestConfiguration.class);
You can avoid this check by searching for the `@Configuration` annotation being meta present.

````java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Configuration // <---
@TestComponent
public @interface TestConfiguration {
````

See also `AnnotationUtils.findAnnotation(...)`

2021-09-12 16:30 UTC, a-simeshin commented on grpc-client-spring-boot-autoconfigure/build.gradle
> +    api 'org.springframework.boot:spring-boot-starter-test'
Removed

2021-09-12 16:32 UTC, a-simeshin commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +        final TestConfiguration[] testConfigurationAnnotation = clazz.getAnnotationsByType(TestConfiguration.class);
Thanks for advice! ``AnnotationUtils.findAnnotation(...)`` works well, I didn't even know that it can work at the class level.
Done

2021-09-12 17:38 UTC, a-simeshin commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +                    log.warn("Could not register and autowire bean: {}", beanNameToCreate, e);
It works С:
Add test to check bean conflict and test for simultaneous use ``@GrpcClient`` with custom bean and ``@GrpcClientBean`` in one ``@Configuration`` class.

2021-09-14 20:55 UTC, a-simeshin commented
@ST-DDT would you be so kind to final review?

2021-09-14 21:31 UTC, ST-DDT requested changes
Sorry, for the delay with the review. I'm currently quite busy so I can only do a fast pass. I hope that I have more time next weekend.

2021-09-14 21:31 UTC, ST-DDT commented on docs/en/client/configuration.md
> +configuration class, but it`s still possible.
```suggestion
configuration class, but it's still possible.
```

2021-09-14 21:31 UTC, ST-DDT commented on docs/en/client/configuration.md
> +This should significantly help with ``@Autowire`` and ``@Qualifier`` because default annotation``@GrpcClient`` is
AFAIK these can all use single backticks '`'

2021-09-14 21:31 UTC, ST-DDT commented on docs/en/client/configuration.md
> +}
Something is wrong with the indentation here.

2021-09-14 21:31 UTC, ST-DDT commented on docs/en/client/getting-started.md
> +  ``@Qualifier``, required annotation ``@Configuration`` or inherited, for example ``@TestConfiguration``.
IMO there is no need to mention inherited `@Configuration`s (e.g. `@TestConfiguration`), as I assume that it matches the expectation. (Both here and above)

2021-09-14 21:31 UTC, ST-DDT commented on docs/en/client/getting-started.md
> +  The annotation should help with multiple registration ``@GrpcClient`` to the spring context.
This section is unneccessary, just mention that the `@GrpcClientBean` is repeatable.

2021-09-14 21:31 UTC, ST-DDT commented on docs/en/client/getting-started.md
> +> the first example for same configuration class, but it`s still possible.
```suggestion
> the previous example for same configuration class, but it`s still possible.
```

2021-09-14 21:31 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +@Slf4j
AFAICT this logger is currently unused

2021-09-17 16:16 UTC, a-simeshin commented on docs/en/client/configuration.md
> +configuration class, but it`s still possible.
Done

2021-09-17 16:17 UTC, a-simeshin commented on docs/en/client/configuration.md
> +This should significantly help with ``@Autowire`` and ``@Qualifier`` because default annotation``@GrpcClient`` is
Replaced

2021-09-17 16:18 UTC, a-simeshin commented on docs/en/client/configuration.md
> +}
Fixed

2021-09-17 16:18 UTC, a-simeshin commented on docs/en/client/getting-started.md
> +  The annotation should help with multiple registration ``@GrpcClient`` to the spring context.
Removed

2021-09-17 16:18 UTC, a-simeshin commented on docs/en/client/getting-started.md
> +> the first example for same configuration class, but it`s still possible.
Done

2021-09-17 16:19 UTC, a-simeshin commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +@Slf4j
Removed annotation and import

2021-09-17 16:19 UTC, a-simeshin commented on docs/en/client/getting-started.md
> +  ``@Qualifier``, required annotation ``@Configuration`` or inherited, for example ``@TestConfiguration``.
Removed in both files

2021-09-17 17:31 UTC, ST-DDT requested changes
Final review before merge. 👍

2021-09-17 17:31 UTC, ST-DDT commented on docs/en/client/configuration.md
> +````
I would recommend merging both chapters into one, as the `@GrpcClientBeans` is not that important for the developer.

```suggestion
````java
@Configuration
@GrpcClientBean(
    clazz = TestServiceBlockingStub.class,
    beanName = "blockingStub",
    client = @GrpcClient("test")
)
@GrpcClientBean(
    clazz = FactoryMethodAccessibleStub.class,
    beanName = "accessibleStub",
    client = @GrpcClient("test"))
public class YourCustomConfiguration {

    @Bean
    FooService fooServiceBean(@Autowired TestServiceGrpc.TestServiceBlockingStub blockingStub) {
        return new FoobarService(blockingStub);
    }

}

@Service
@AllArgsConsturtor
public class BarService {

    private FactoryMethodAccessibleStub accessibleStub;

    public String receiveGreeting(String name) {
        HelloRequest request = HelloRequest.newBuilder()
                .setName(name)
                .build();
        return accessibleStub.sayHello(request).getMessage();
    }

}
````
```

2021-09-17 17:31 UTC, ST-DDT commented on docs/en/client/configuration.md
> +  - [GrpcClientBeans](#grpcclientbeans)
```suggestion
```

2021-09-17 17:31 UTC, ST-DDT commented on docs/en/client/configuration.md
> +configuration class, but it's still possible.
```suggestion
This annotation is used to create injectable beans from your otherwise non-injectable `@GrpcClient` instances.
The annotation can be repeatedly added to any of your `@Configuration` classes.

> **Note:** We recommend using either `@GrpcClientBean`s or fields annotated with `@GrpcClient` throughout your
> application, as mixing the two might cause confusion for future developers.
```

2021-09-17 17:31 UTC, ST-DDT commented on docs/en/client/getting-started.md
> +  `@Qualifier`, required annotation `@Configuration`. Also, this annotation is repeatable using `@GrpcClientBeans`.
```suggestion
  The annotation helps to register `@GrpcClient` beans in the Spring context to be used with `@Autowired` and
  `@Qualifier`. The annotation can be repeatedly added to any of your `@Configuration` classes.
```

2021-09-17 17:31 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +                for (final GrpcClientBean beanClientIterator : clazz.getAnnotationsByType(GrpcClientBean.class)) {
How about calling the field simply `annotation`, as it isn't really an `Iterator`?

2021-09-17 17:31 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +     * @return name
```suggestion
     * Gets the bean name from the given annotation.
     *
     * @param grpcClientBean The annotation to extract it from.
     * @return The extracted name.
```

2021-09-17 17:31 UTC, ST-DDT commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +     * @return does the class have an annotation or not
```suggestion
     * Checks whether the given class is annotated with {@link Configuration}.
     *
     * @param clazz The class to check.
     * @return True, if the given class is annotated with {@link Configuration}. False otherwise.
```

2021-09-17 17:48 UTC, a-simeshin commented on grpc-client-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/client/inject/GrpcClientBeanPostProcessor.java
> +                for (final GrpcClientBean beanClientIterator : clazz.getAnnotationsByType(GrpcClientBean.class)) {
You are definitely right! Renamed

2021-09-17 18:09 UTC, a-simeshin commented
@ST-DDT it seems that we have a flaky test - MetricCollectingInterceptorTest > testMetricsFailedCall() failed in different builds with just md changes:

- https://github.com/yidongnan/grpc-spring-boot-starter/pull/580/checks?check_run_id=3635062828
- https://github.com/yidongnan/grpc-spring-boot-starter/pull/580/checks?check_run_id=3635074122
- https://github.com/yidongnan/grpc-spring-boot-starter/pull/580/checks?check_run_id=3635118686

Have I to commit something to rerun build or there is more another "handy" way?
Should I create issue and try to fix and different PR?

2021-09-17 21:57 UTC, ST-DDT commented
> @ST-DDT it seems that we have a flaky test - MetricCollectingInterceptorTest > testMetricsFailedCall() failed in different builds with just md changes:

I am aware of that test, I already improved it multiple times to "fail less", but the error still prevails and I'm not sure why. Currently I get a ~1% chance of a failure in my local builds. Sometimes I suspect that it only happens at specific times.

> Have I to commit something to rerun build or there is more another "handy" way?

I have a re-run button in travis, that I can use to execute the checks again. Not sure, whether you have it as well.

> Should I create issue and try to fix and different PR?

Feel free to have a try (once this one is merged).

2021-09-18 12:48 UTC, ST-DDT approved these changes

2021-09-18 12:48 UTC, ST-DDT commented
Thanks for your contribution!

2021-09-18 12:50 UTC, merged

2022-02-25 19:18 UTC, dileep-alla-by commented
i am not able to initialize grpc stub by using @bean annotation 

error:- Parameter 0 of constructor in com.grpc.ContractRatesClientService required a bean of type 'com.grpc.v1.ReactorContractRatesGrpc$ReactorContractRatesStub' that could not be found. 

can  you help whats is the issue?

@GrpcClientBean(clazz = ReactorContractRatesStub.class, client = @GrpcClient("rating-data-service"))
@Configuration
public class RatingOrchestrationConfig {

    @Bean
    public ContractRatesClientService contractRatesClient(ReactorContractRatesStub contractRatesStub, RatesProtobufMapper ratesProtobufMapper) {
        return new ContractRatesClientService(contractRatesStub, ratesProtobufMapper);
    }
}


@Service
@Slf4j
@RequiredArgsConstructor
public class ContractRatesClientService {

    private final ReactorContractRatesGrpc.ReactorContractRatesStub contractRatesStub;
    private final RatesProtobufMapper ratesProtobufMapper;
}

2022-02-25 19:53 UTC, ST-DDT commented
Please try do move the `@GrpcClientBean` to its own config and order `RatingOrchestrationConfig` after that config.

It looks like I need to improve the initialization/bean declaration order somehow.

------------------

EDIT: Please try removing `@Service` from the service, as this might interfere with bean initialization order. (Or order it after the `RatingOrchestrationConfig`)